[package]
authors = ["Jeremy Soller <jackpot51@gmail.com>"]
description = "The Orbital Windowing System and Compositor"
license-file = "LICENSE"
name = "orbital"
readme = "README.md"
repository = "https://gitlab.redox-os.org/redox-os/orbital"
version = "0.1.0"

[dependencies]
failure = "0.1.1"
orbclient = "0.3.27"
orbfont = "0.1"
redox_syscall = { git = "https://gitlab.redox-os.org/redox-os/syscall", rev = "4115e0f43547449ce56f7d7749732813e9505955" }
serde = "0.9"
serde_derive = "0.9"
toml = "0.3"

[dependencies.orbital-core]
path = "orbital-core"
